---
title: "College Scratch"
author: "Corbin B; Matthew W"
format: pdf
editor: visual
---

```{r}

library(tidyverse)

```

```{r}

sal_df <- vroom::vroom("Salary.csv")

sal_df <- sal_df |>
  mutate(
    MajorCategory = factor(MajorCategory),
    Sex = factor(Sex)
  )

sal_lm<-lm(Salary~ .,sal_df)
```

## Impact of GPA

## Salaries Across Majors - Matthew

```{r}

# linear model predicting Salary by Major Category
maj_lm <- lm(Salary ~ MajorCategory, data = sal_df)
summary(maj_lm)


```

Yes, we see that "Engineering", "Computers and Mathematics", and "Physical Sciences" make the most when ignoring all other varaibles.

## Salaries for Women and Men

## Other Factors - Matthew

```{r}

# linear model using all predictors and no interactions
sal_lm<-lm(Salary~ .,sal_df)

# linear model using all predictors and interactions found to be significant:
sal_interaction_lm <- lm(Salary ~ MajorCategory * Sex + MajorCategory * GPA, data = sal_df)


anova(sal_lm, sal_interaction_lm)
summary(sal_interaction_lm)



```
